# Generated by Django 3.1 on 2020-08-05 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.CharField(default='images/default_post.png', max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='img',
            field=models.CharField(default='images/default_city.png', max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.CharField(default='images/default_profile.png', max_length=300),
        ),
    ]
