# Generated by Django 3.1 on 2020-08-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200806_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='img',
            field=models.CharField(default='images/default_city.jpg', max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.CharField(default='images/default_post.jpg', max_length=300),
        ),
    ]
